# Generated by Django 5.2.6 on 2025-09-13 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GitHubPerfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=255, verbose_name='Nome')),
                ('login', models.CharField(max_length=255, verbose_name='Login (Nome original)')),
                ('img', models.URLField(verbose_name='Avatar URL')),
                ('site', models.URLField(verbose_name='URL do Perfil')),
                ('bio', models.CharField(blank=True, max_length=160, verbose_name='Bio')),
            ],
            options={
                'verbose_name': 'Perfil do GitHub',
                'verbose_name_plural': 'Lista de perfis GitHub',
            },
        ),
    ]
