# Generated by Django 5.2.6 on 2025-09-13 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='githubperfil',
            name='login',
            field=models.CharField(max_length=255, unique=True, verbose_name='Login (Nome original)'),
        ),
    ]
