# Generated by Django 5.2.6 on 2025-09-14 06:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_githubperfil_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='githubperfil',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='githubperfil',
            name='img',
        ),
        migrations.RemoveField(
            model_name='githubperfil',
            name='site',
        ),
        migrations.CreateModel(
            name='GitHubEstatisticas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.CharField(blank=True, max_length=160, verbose_name='Bio')),
                ('img', models.URLField(verbose_name='Avatar URL')),
                ('site', models.URLField(verbose_name='URL do Perfil')),
                ('perfil', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.githubperfil')),
            ],
        ),
    ]
