# Generated by Django 5.2.6 on 2025-09-14 06:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_githubperfil_bio_remove_githubperfil_img_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GitHubNome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=255, verbose_name='Nome')),
                ('login', models.CharField(max_length=255, unique=True, verbose_name='Login (Nome original)')),
            ],
            options={
                'verbose_name': 'Perfil do GitHub',
                'verbose_name_plural': 'Lista de perfis GitHub',
            },
        ),
        migrations.CreateModel(
            name='GitHubInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.CharField(blank=True, max_length=160, verbose_name='Bio')),
                ('img', models.URLField(verbose_name='Avatar URL')),
                ('site', models.URLField(verbose_name='URL do Perfil')),
                ('perfil', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.githubnome')),
            ],
            options={
                'verbose_name': 'Estatisticas do GitHub',
                'verbose_name_plural': 'Estatisticas do GitHub',
            },
        ),
        migrations.DeleteModel(
            name='GitHubEstatisticas',
        ),
        migrations.DeleteModel(
            name='GitHubPerfil',
        ),
    ]
